resources:
- ../base
- env-ops-configmap.yaml
- r3e82d7c/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r3e82d7c/revision-patch.yaml
  target:
    kind: Service
- path: r3e82d7c/routing-patch.yaml
  target:
    kind: Service
