apiVersion: v1
kind: LimitRange
metadata:
  name: limit-develop
  namespace: development  
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1024Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
